export const images = [
  {
    id: 1,
    title: 'Lambor Hill',
    category: 'nature',
    imageUrl: '/images/landimage001.webp',
  },
  {
    id: 2,
    title: 'Mistwood Lake',
    category: 'nature',
    imageUrl: '/images/landimage002.webp',
  },
  {
    id: 3,
    title: 'Aether Lake',
    category: 'nature',
    imageUrl: '/images/landimage003.webp',
  },
  {
    id: 4,
    title: "Kel's Falls",
    category: 'nature',
    imageUrl: '/images/landimage004.webp',
  },
  {
    id: 5,
    title: 'Silvercrest Prairie',
    category: 'nature',
    imageUrl: '/images/landimage005.webp',
  },
  {
    id: 6,
    title: 'Taurie Plains',
    category: 'nature',
    imageUrl: '/images/landimage006.webp',
  },
  {
    id: 7,
    title: 'Azure River',
    category: 'nature',
    imageUrl: '/images/landimage007.webp',
  },
  {
    id: 8,
    title: 'Lambor Lake',
    category: 'nature',
    imageUrl: '/images/landimage008.webp',
  },
  {
    id: 9,
    title: 'Birchwood Beach',
    category: 'nature',
    imageUrl: '/images/landimage009.webp',
  },
  {
    id: 10,
    title: 'Cray Lagoon',
    category: 'nature',
    imageUrl: '/images/landimage010.webp',
  },
  {
    id: 11,
    title: 'Cerulean Shore',
    category: 'nature',
    imageUrl: '/images/landimage011.webp',
  },
  {
    id: 12,
    title: 'Cloudridge Beach',
    category: 'nature',
    imageUrl: '/images/landimage012.webp',
  },
  {
    id: 13,
    title: 'Maplecrest Hills',
    category: 'nature',
    imageUrl: '/images/landimage013.webp',
  },
  {
    id: 14,
    title: 'Oakshadow Pond',
    category: 'nature',
    imageUrl: '/images/landimage014.webp',
  },
  {
    id: 15,
    title: 'Sunfire Lough',
    category: 'nature',
    imageUrl: '/images/landimage015.webp',
  },
  {
    id: 16,
    title: 'Loch Vinecliff',
    category: 'nature',
    imageUrl: '/images/landimage016.webp',
  },
  {
    id: 17,
    title: 'Amber Lake',
    category: 'nature',
    imageUrl: '/images/landimage017.webp',
  },
  {
    id: 18,
    title: 'Phoenix Valley',
    category: 'nature',
    imageUrl: '/images/landimage018.webp',
  },
  {
    id: 19,
    title: 'Silent Vale',
    category: 'nature',
    imageUrl: '/images/landimage019.webp',
  },
  {
    id: 20,
    title: 'Frosted Hill',
    category: 'nature',
    imageUrl: '/images/landimage020.webp',
  },
  {
    id: 21,
    title: 'Sunset Prairie',
    category: 'nature',
    imageUrl: '/images/landimage021.webp',
  },
  {
    id: 22,
    title: 'Teatree Falls',
    category: 'nature',
    imageUrl: '/images/landimage022.webp',
  },
  {
    id: 23,
    title: 'Verdant Falls',
    category: 'nature',
    imageUrl: '/images/landimage023.webp',
  },
  {
    id: 24,
    title: 'Lustrous Grove',
    category: 'nature',
    imageUrl: '/images/landimage024.webp',
  },
];
